package com.lambdaschool.todos.exceptions;

import lombok.Data;
import org.springframework.http.HttpStatus;

import java.util.Date;

/**
 * An error generated by the API
 */
@Data
public class Error {
  private Date timestamp;
  private HttpStatus httpStatus;
  private String message;
  private String details;

  /**
   * Default Constructor automatically sets the timestamp on the error.
   *
   * @param httpStatus  HTTP status code
   * @param message     A user friendly error message
   * @param details     Additional details that could help resolve the error
   */
  public Error(HttpStatus httpStatus, String message, String details) {
    this.timestamp = new Date();
    this.httpStatus = httpStatus;
    this.message = message;
    this.details = details;
  }
}
