CREATE TABLE IF NOT EXISTS Users (
    UserId   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    UserName STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS ToDo (
    ToDoId      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Description STRING NOT NULL,
    DateStarted DATETIME,
    Completed   BOOLEAN,
    UserId      INTEGER REFERENCES Users (UserId) NOT NULL
);