CREATE TABLE IF NOT EXISTS User (
    UserId   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    UserName STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS ToDo (
    ToDoId      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Description STRING NOT NULL,
    DateStarted DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Completed   BOOLEAN,
    UserId      INTEGER REFERENCES User (UserId) NOT NULL
);